# Computational Finance I
**Lab-Exercise No. 1**


# P1: Trinomial Tree
In the lecture we mentioned that a binomial model can be generalized to a trinomial model. In a trinomial model we need to consider three stock price developments: in one period the price increases by a factor of $u$ with the probability $p_u$, descreases by a factor of $d$ with the probability $p_d$, or remains unchanged with the probability $1−p_u −p_d$. The trinomial model can be built in a similar way to the binomial model, e.g., by matching the expectation and the variance and using $ud = 1$ we obtain:
    $$ u = e^{\sigma\sqrt{2\Delta t}}, \quad d = e^{-\sigma\sqrt{2\Delta t}}, \quad p_d = \left( \frac{ e^{\sigma\sqrt{\frac{\Delta t}{2}}} - e^{r\frac{\Delta t}{2}} }{e^{\sigma\sqrt{\frac{\Delta t}{2}}} - e^{-\sigma\sqrt{\frac{\Delta t}{2}}}} \right)^2, \quad \quad p_u = \left( \frac{ e^{r\frac{\Delta t}{2}} - e^{-\sigma\sqrt{\frac{\Delta t}{2}}}}{e^{\sigma\sqrt{\frac{\Delta t}{2}}} - e^{-\sigma\sqrt{\frac{\Delta t}{2}}}} \right)^2.$$

For the programming task write the corresponding Python functions that are asked in each section below.

**Return the solutions of the programming task $\href{https://moodle.uni-wuppertal.de/mod/assign/view.php?id=516765}{{here}}$ until Thursday, May 21. The assignment can be done in groups of 1-2 persons. The solution should be presented within the following 2 weeks via an online arranged ZOOM meeting with M.Sc. Lorenc Kapllani.**

## Write your data

In [147]:
print("First Name: "+"Zhirui")
print("Sure Name: "+"Tang")
print("Matriculation number: " +"1942800")
print("E-mail: "+"zhirui.tang@uni-wuppertal.de")
print("Degree Type: "+"Master") # Bachelor or Master
print("Degree Name: "+"Master of Science in Computer Simulation in Science") # E.g. Master of Science in Computer Simulation in Science

First Name: Zhirui
Sure Name: Tang
Matriculation number: 1942800
E-mail: zhirui.tang@uni-wuppertal.de
Degree Type: Master
Degree Name: Master of Science in Computer Simulation in Science


## Import all necessary modules

In [148]:
import math
import numpy as np

## Test Parameters

In [224]:
# Input parameters
sigma = 0.2
K = 100
S0 = 100
N = 4
r = 0.05
T = 1
d_t = T / N

# Start coding
**Note:** 
* Add code where you find the comment "# Add code here"
* Get the same output as it is presented in the Markdown text **Expected Output:**

## Define a function to calculate the up and down factors

In [150]:
def calc_ud(sigma, d_t):
    """
    Function that calculates the factors in the trinomial model

    Input: sigma -> volatility 
            d_t  -> time step size

    Output: u -> upward movement
            d -> downward movement

    """
    # Add code here
    u = math.exp(sigma*math.sqrt(2*d_t))
    d = math.exp(-sigma*math.sqrt(2*d_t))
    return u, d

In [152]:
# Calculate upward and downward movements
# Add code here
[u, d] = calc_ud(sigma, d_t)
print('u = %.6f,' %u, 'd = %.6f' %d) #looks no good 

u = 1.151910, d = 0.868123


**Expected Output:**
`u = 1.151910, d = 0.868123`

## Define a function to calculate the probabilities in the trinomial model

In [153]:
def calc_prob(r, sigma, d_t):
    """
    Function that calculates the probabilities in the trinomial model

    Input: r     -> interest rate
           sigma -> volatility
           d_t   -> time step size

    Output: p_u -> probability for upward movement
            p_d -> probability for downward movement
            p_m -> probability for no change

    """
    # Add code here
    x1 = math.exp(sigma*math.sqrt(d_t/2))
    x2 = math.exp(-sigma*math.sqrt(d_t/2))
    y = math.exp(r*d_t/2)
    p_u = ((y-x2)/(x1-x2))**2
    p_d = ((x1-y)/(x1-x2))**2
    p_m = 1 - p_u - p_d
    return p_u, p_d, p_m

In [154]:
# Calculate probabilities
# Add code here
[p_u, p_d, p_m] = calc_prob(r, sigma, d_t)
print('p_u = %.6f,' %p_u, 'p_d = %.6f,' %p_d, 'p_m = %.6f' %p_m)

p_u = 0.277334, p_d = 0.224084, p_m = 0.498582


**Expected Output:**
`p_u = 0.277334, p_d = 0.224084, p_m = 0.498582`

## Define a function to calculate the stock prices in the trinomial model

In [155]:
def stock_price_trinom(S0, N, u, d):
    
    """
    Function that calculates the stock prices in the trinomial model
    
    Input: S0 -> Initial Stock Price
           u  -> upward movement
           d  -> downward movement
           N  -> Number of time periods
       
    Output: S -> Upper triangular matrix of Stock prices with tirnomial model
    """
    # Add code here
    St = np.zeros([2*N+1,N+1])
    #Python indexing starts at 0, not 1.
    St[0][0] = S0
    for i in range(N):
        for k in range(2*i+1):
            St[k][i+1] = St[k][i]*u
            St[k+1][i+1] = St[k][i]
            St[k+2][i+1] = St[k][i]*d
    return St
            

In [202]:
# Calculate stock prices
S = stock_price_trinom(S0, N, u, d)
print("Stock Price\n", S)

Stock Price
 [[100.         115.19099102 132.68964411 152.84651603 176.06541655]
 [  0.         100.         115.19099102 132.68964411 152.84651603]
 [  0.          86.81234454 100.         115.19099102 132.68964411]
 [  0.           0.          86.81234454 100.         115.19099102]
 [  0.           0.          75.36383164  86.81234454 100.        ]
 [  0.           0.           0.          75.36383164  86.81234454]
 [  0.           0.           0.          65.42510919  75.36383164]
 [  0.           0.           0.           0.          65.42510919]
 [  0.           0.           0.           0.          56.7970712 ]]


**Expected Output:**

`Stock Prices`

`[[100.         115.19099102 132.68964411 152.84651603 176.06541655]
 [  0.         100.         115.19099102 132.68964411 152.84651603]
 [  0.          86.81234454 100.         115.19099102 132.68964411]
 [  0.           0.          86.81234454 100.         115.19099102]
 [  0.           0.          75.36383164  86.81234454 100.        ]
 [  0.           0.           0.          75.36383164  86.81234454]
 [  0.           0.           0.          65.42510919  75.36383164]
 [  0.           0.           0.           0.          65.42510919]
 [  0.           0.           0.           0.          56.7970712 ]]`

## Define a function to calculate the European option price using trinomial model

In [227]:
def priceTriEuro(N, K, r, S, p_u, p_d, p_m, d_t):
    """
    Function that calculates the European option price using trinomial model
    
    Input: N     -> Number of time periods
           K     -> Strike price
           r     -> Interst rate
           S     -> Upper triangular matrix
           p_u   -> probability for upward movement
           p_d   -> probability for downward movement
           p_m   -> probability for no change
           d_t   -> time step size
       
    Output: C -> European Call option 
            P -> European Put option 

    """
    # Add code here
    #Initialization
    C = np.zeros([2*N+1, N+1])
    P = np.zeros([2*N+1, N+1])
    
    #Computation of the payoff
    for i in range(2*N+1):
        sk = S[i][N] - K
        if abs(sk) < 1e-8:
            sk = 0
        C[i][N] = max(sk, 0)
        P[i][N] = max(-sk, 0)
    
    #Backward iteration
    for i in range(N, 0, -1):
        for k in range(2*i-1):
            C[k][i-1] = math.exp(-d_t*r)*(p_u*C[k][i] + p_m*C[k+1][i] + p_d*C[k+2][i])
            P[k][i-1] = math.exp(-d_t*r)*(p_u*P[k][i] + p_m*P[k+1][i] + p_d*P[k+2][i])
    Vp=P[0][0]
    
    return C, P, Vp

In [229]:
# Calculate European call and put values
# Add code here
C, P, _ = priceTriEuro(N, K, r, S, p_u, p_d, p_m, d_t)
print("European Call\n\n", C, '\n')
print("European Put\n\n", P, '\n')

European Call

 [[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]] 

European Put

 [[ 5.32804187  1.22102826  0.          0.          0.        ]
 [ 0.          4.810315    0.64584791  0.          0.        ]
 [ 0.         11.86204809  4.08052515  0.          0.        ]
 [ 0.          0.         11.85820287  2.91842761  0.        ]
 [ 0.          0.         22.16715956 11.94543551  0.        ]
 [ 0.          0.          0.         23.39394841 13.18765546]
 [ 0.          0.    

**Expected Output:**

`European Call`

`[[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]`

`European Put`

`[[ 5.32804187  1.22102826  0.          0.          0.        ]
 [ 0.          4.810315    0.64584791  0.          0.        ]
 [ 0.         11.86204809  4.08052515  0.          0.        ]
 [ 0.          0.         11.85820287  2.91842761  0.        ]
 [ 0.          0.         22.16715956 11.94543551  0.        ]
 [ 0.          0.          0.         23.39394841 13.18765546]
 [ 0.          0.          0.         33.33267086 24.63616836]
 [ 0.          0.          0.          0.         34.57489081]
 [ 0.          0.          0.          0.         43.2029288 ]]`

## Define a function to calculate the American option price using trinomial model

In [225]:
def priceTriAmer(N, K, r, S, p_u, p_d, p_m, d_t):
    """
    Function that calculates the American option price using trinomial model
    
    Input: N     -> Number of time periods
           K     -> Strike price
           r     -> Interst rate
           S     -> Upper triangular matrix
           p_u   -> probability for upward movement
           p_d   -> probability for downward movement
           p_m   -> probability for no change
           d_t   -> time step size
       
    Output: C -> American Call option 
            P -> American Put option 

    """
    # Add code here
    #Initialization
    C = np.zeros([2*N+1, N+1])
    P = np.zeros([2*N+1, N+1])
    
    #Computation of the payoff
    for i in range(2*N+1):
        sk = S[i][N] - K
        if abs(sk) < 1e-8:
            sk = 0
        C[i][N] = max(sk, 0)
        P[i][N] = max(-sk, 0)
    
    #Backward iteration
    for i in range(N, 0, -1):
        for k in range(2*i-1):
            sk = S[k][i-1]-K
            if abs(sk) < 1e-8:
                sk = 0
            Cf = math.exp(-d_t*r)*(p_u*C[k][i] + p_m*C[k+1][i] + p_d*C[k+2][i])
            C[k][i-1] = max(max(sk,0), Cf)
            
            Pf = math.exp(-d_t*r)*(p_u*P[k][i] + p_m*P[k+1][i] + p_d*P[k+2][i])
            P[k][i-1] = max(max(-sk,0), Pf)
    Vp=P[0][0]
    
    return C, P, Vp

In [230]:
# Calculate American call and put values
# Add code here
C, P, _ = priceTriAmer(N, K, r, S, p_u, p_d, p_m, d_t)
print("American Call\n\n", C, '\n')
print("American Put\n\n", P, '\n')

American Call

 [[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]] 

American Put

 [[ 5.84957502  1.28186433  0.          0.          0.        ]
 [ 0.          5.23988204  0.64584791  0.          0.        ]
 [ 0.         13.18765546  4.35542837  0.          0.        ]
 [ 0.          0.         13.18765546  2.91842761  0.        ]
 [ 0.          0.         24.63616836 13.18765546  0.        ]
 [ 0.          0.          0.         24.63616836 13.18765546]
 [ 0.          0.    

**Expected Output:**

`American Call`

`[[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]`

`American Put`

`[[ 5.84957502  1.28186433  0.          0.          0.        ]
 [ 0.          5.23988204  0.64584791  0.          0.        ]
 [ 0.         13.18765546  4.35542837  0.          0.        ]
 [ 0.          0.         13.18765546  2.91842761  0.        ]
 [ 0.          0.         24.63616836 13.18765546  0.        ]
 [ 0.          0.          0.         24.63616836 13.18765546]
 [ 0.          0.          0.         34.57489081 24.63616836]
 [ 0.          0.          0.          0.         34.57489081]
 [ 0.          0.          0.          0.         43.2029288 ]]`

## Comparing European and American option values calculated with Trinomial Model from the exact Solution

In [245]:
# Calculate European and American put values for different N and compare to exact solution
# Exact Values
E_P_ex = 5.5735
A_P_ex = 6.0624
N = [4, 16, 64, 256, 512, 1024]

# Add code here
print('%-8s' %"N", '%-16s' %"E_P_ex", '%-16s' %"E_P_app", '%-16s' %"err_E_P", \
      '%-16s' %"A_P_ex", '%-16s' %"A_P_app", '%-16s' %"err_A_P")
print('---------------------------------------------------------------------------------------------------------')

for n in N:
    d_t = T / n
    [u, d] = calc_ud(sigma, d_t)
    [p_u, p_d, p_m] = calc_prob(r, sigma, d_t)
    S = stock_price_trinom(S0, n, u, d)
    _, _, E_P_app = priceTriEuro(n, K, r, S, p_u, p_d, p_m, d_t) 
    _, _, A_P_app = priceTriAmer(n, K, r, S, p_u, p_d, p_m, d_t)
    print('%-8s' %n, '%-16.6f' %E_P_ex, '%-16.6f' %E_P_app, '%-16.6E' %abs(E_P_ex-E_P_app),\
          '%-16.6f' %A_P_ex, '%-16.6f' %A_P_app, '%-16.6E' %abs(A_P_ex-A_P_app))


N        E_P_ex           E_P_app          err_E_P          A_P_ex           A_P_app          err_A_P         
---------------------------------------------------------------------------------------------------------
4        5.573500         5.328042         2.454581E-01     6.062400         5.849575         2.128250E-01    
16       5.573500         5.511288         6.221195E-02     6.062400         6.031125         3.127492E-02    
64       5.573500         5.557919         1.558139E-02     6.062400         6.077022         1.462235E-02    
256      5.573500         5.569621         3.878723E-03     6.062400         6.087340         2.493992E-02    
512      5.573500         5.571573         1.926589E-03     6.062400         6.088906         2.650645E-02    
1024     5.573500         5.572550         9.503432E-04     6.062400         6.089652         2.725172E-02    


**Expected Output:**
![title](trinom_tree.png)

In [ ]:
# feel free to use this cell for additional tests

In [ ]:
# feel free to use this cell for additional tests

In [ ]:
# feel free to use this cell for additional tests

In [ ]:
# feel free to use this cell for additional tests

In [ ]:
# feel free to use this cell for additional tests